version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
