version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    automerge: true
    automerge-type: "patch"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
