name: Lint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run type check (lib)
        run: npm run type-check:lib

      - name: Run type check (app)
        run: npm run type-check:app

      - name: Build (lib)
        run: npm run build:lib

      - name: Build (app)
        run: npm run build:app
